#define             MAIN            1
#define             IDENT           2
#define             ENTERO          3
#define             SEMICOLON       4
#define             COLON           5
#define             DOT             6
#define             COMMA           7
#define             PLUSOP          8
#define             MINUSOP         9
#define             STAR            10
#define             SLASH           11
#define             LPAREN          12
#define             RPAREN          13
#define             ASSIGNOP        14
#define             STRING          15
#define             PROGRAM         16
#define             FUNCTION        17
#define             CONST           18
#define             VAR             19
#define             INTEGER         20
#define             BEGINN          21
#define             END             22
#define             IF              23
#define             THEN            24
#define             ELSE            25
#define             WHILE           26
#define             DO              27
#define             FOR             28
#define             TO              29
#define             WRITE           30
#define             READ            31